### ISSUE TITLE
[ADD] 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by Ssamssamukja** [Link-zip/Link-zip-FE#1]
## 📝 개요
- 개발 초기 세팅

## ✔️ To-Do
- [ ] gradle 기초 세팅
- [ ] manifest 기초 세팅
- [ ] themes 기초 세팅
- [ ] 모듈 세팅
- [ ] Extension 추가
- [ ] 디자인 시스템 적용
- [ ] bottom navigation 연결

## 👀 ETC
- 참고자료 등 기타 내용 작성
