### ISSUE TITLE
[Feat] Link & Text 저장 기능 개발

### ISSUE THREAD

**Issue by ekgml001** [Link-zip/Link-zip-FE#30]
## 📝 개요
- Link & Text 저장 기능 개발

## ✔️ To-Do
- [ ]  화면 연결
- [ ]  date picker 연결
- [ ]  time picker 연결
- [ ]  zip item 연결

## 👀 ETC
- 참고자료 등 기타 내용 작성
