### ISSUE TITLE
[feat / #77] Zip 부가적인 부분 수정

### ISSUE THREAD

**Issue by leesumin0526** [Link-zip/Link-zip-FE#77]
## 📝 개요
- 자세한 개요 작성

## ✔️ To-Do
- [ ] Zip 이동 후 Toast 뜨는 시점, api 호출 완료 후로 수정
- [x] Zip 이동 dialog X 버튼 누르면 dismiss 되도록 수정
- [x] OpenZip DropDown 버튼 삭제

## 👀 ETC
- 참고자료 등 기타 내용 작성
