### ISSUE TITLE
[feat] Zip 부가적인 부분 수정

### ISSUE THREAD

**Issue by leesumin0526** [Link-zip/Link-zip-FE#85]
## 📝 개요
- 자세한 개요 작성

## ✔️ To-Do
- [x] Zip 이동 또는 삭제 했을 때 위쪽의 OpenZipFragment의 링크개수 실시간 반영 안 됨
- [x] 저장할 Zip 선택하기 링크 개수 실시간 반영 안됨 <- 1과 원인 같음
- [x] OpenZip DropDown 버튼 삭제..
- [x] 알림 페이지 Api 연결
- [x] Zip 한번에 여러개 이동 가능하게 구현

## 👀 ETC
- 참고자료 등 기타 내용 작성
