### ISSUE TITLE
[Feat] 링크텍스트/알림 페이지 오류

### ISSUE THREAD

**Issue by ekgml001** [Link-zip/Link-zip-FE#86]
## 📝 개요
- 링크텍스트/알림 페이지 오류 해결하기

## ✔️ To-Do
- [ ] 알림 페이지에서 이동한 링크 페이지에서 뒤로가기 시 강제종료되는 문제
- [x] 링크/텍스트 생성할 때 고른 zip ID 받아오기
- [x] ai 요약 Loading 시간 연동하기
- [x] ZIp 선택 안 하면 ‘다음’ 버튼 안 눌리게 하기
- [x] date picker UI 수정

## 👀 ETC
- 참고자료 등 기타 내용 작성
